{% set name = "jupyterlab-latex" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_latex/jupyterlab_latex-{{ version }}.tar.gz
  sha256: e5555725d432f30725140746cb8ddb2d57d404f07c8e741ff18256183af993b9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - notebook

test:
  imports:
    - jupyterlab_latex

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: JupyterLab extension for live editing of LaTeX documents

  description: |
    An extension for JupyterLab which allows for live-editing of LaTeX 
    documents.
  doc_url: https://github.com/jupyterlab/jupyterlab-latex/blob/master/docs/advanced.md
  dev_url: https://github.com/jupyterlab/jupyterlab-latex

extra:
  recipe-maintainers:
    - jan-janssen
